### ISSUE TITLE
Pre-compute results

### ISSUE THREAD

**Issue by maqsoodrajput** [DestinE-Climate-DT/Climate-DT-catalog#108]
Suggestion in the group meeting: try to put different variables together by `*` in a dataset without variable as a intake kwargs. 

I tested the catalog by removing the `variable` keyword from `Climate-DT-catalog/catalogs/climatedt-phase1/catalog/IFS-NEMO/historical-1990.yaml`. 

This `*` works for `aqua-timeseries-annual`, `aqua-timeseries-monthly` and `aqua-atmglobalmean`. 

However, if I put `*` in `aqua-zonalmean`, e.g, `ocean3d_drift/netcdf/IFS-NEMO-historical-1990-lra-r100-monthly_zonal_mean_trend_*_ocean.nc`.

And, I do:
 
```
reader = Reader(model='IFS-NEMO',exp='historical-1990',source='aqua-zonalmean')
data = reader.retrieve('so')
```

, the output has `Dimensions: (lev: 75 lat: 180)`. Here, I am not sure what I am getting exactly.  

![Image](https://github.com/user-attachments/assets/c126e4a7-aa10-4161-8dfb-db8ef67a3818)

For example, there are `arctic`, `atlantic`, `global`, `indian`, `pacific`, `southern`. So, in order to read these different files I must specify these names separately in the catalog. Otherwise, `data = reader.retrieve('atlantic')` gives `No match found for ['atlantic']` warning. 

Branch: [catalog_ensemble](https://github.com/DestinE-Climate-DT/Climate-DT-catalog/blob/catalog_ensemble/catalogs/climatedt-phase1/catalog/IFS-NEMO/historical-1990.yaml)

**Comment by mnurisso** [comment]
For the ocean we're speaking about different regions analyzed, am I correct? So the previous approach make sense, since you're trying otherwise to group not variables, but regions and it's quite probable this may create issues when opening the dataset.

**Comment by maqsoodrajput** [comment]
yes, each region file has different dimensions. Indeed, here the `Reader` groups the regions but not the variables.

**Comment by mnurisso** [comment]
Perfect, I hope it will work soon then, many thanks!

**Comment by maqsoodrajput** [comment]
btw, both give the same output:


```
  aqua-zonalmean:
    driver: netcdf
    description: AQUA analysis ocean3d_drift zonal diagnostics
    args:
      urlpath: 
        - '{{ OUTPUT_AQUA_PATH }}/IFS-NEMO/historical-1990/ocean3d_drift/netcdf/IFS-NEMO-historical-1990-lra-r100-monthly_zonal_mean_trend_{{ region }}_ocean.nc'
      xarray_kwargs:
        combine: 'nested'
        compat: 'override'
    parameters:
      region:
        allowed: ['arctic','atlantic','global','indian','pacific','southern']
        description: AQUA analysis regional ocean3d_drift zonal diagnostics
        type: str
        default: 'atlantic'
    metadata:
      source_grid_name: null
```

Previously:

```
  aqua-zonalmean:
    driver: netcdf
    description: AQUA analysis ocean3d_drift zonal diagnostics
    args:
      urlpath: 
        - '{{ OUTPUT_AQUA_PATH }}/IFS-NEMO/historical-1990/ocean3d_drift/netcdf/IFS-NEMO-historical-1990-lra-r100-monthly_zonal_mean_trend_{{ region }}_ocean.nc'
      xarray_kwargs:
        combine: 'nested'
        compat: 'override'
    parameters:
      region:
        allowed: ['arctic','atlantic','global','indian','pacific','southern']
        description: AQUA analysis regional ocean3d_drift zonal diagnostics
        type: str
        default: 'atlantic'
      _var:
        allowed: ['so','thetao']
        description: AQUA analysis ocean3d_drift zonal diagnostics
        type: str
        default: 'so'
    metadata:
      source_grid_name: null
```
