### ISSUE TITLE
IFS-NEMO specific timeseries in OBS catalog

### ISSUE THREAD

**Issue by jhardenberg** [DestinE-Climate-DT/Climate-DT-catalog#127]
Is it right for the obs catalog to have this entry in `ERA5/era5.yaml`? This looks specific for IFS-NEMO, why in the obs catalog?

```
 aqua-timeseries-monthly:
    driver: netcdf
    description: AQUA analysis timeseries
    args:
      urlpath:
        - '{{ OUTPUT_AQUA_PATH }}/IFS-NEMO/historical-1990/global_time_series/netcdf/global_time_series_timeseries_{{ variable }}_ERA5_era5_mon.nc'
      xarray_kwargs:
        #decode_times: true
        combine: 'nested'
        compat: 'override'
    parameters:
      variable:
        allowed: ['2t', 'avg_tos', 'avg_siconc', 'hcc', 'lcc', 'mcc', 'msl', 'mslhf', 'msnlwrf', 'msnswrf', 'msshf', 'mtnlwrf', 'mtnlwrf+mtnswrf', 'mtnswrf', 'tcc']
        description: Monthly Timeseries variable
        type: str
        default: '2t'
    metadata:
      source_grid_name: null

```
