### ISSUE TITLE
lumi-phase1 IFS-NEMO main.yaml broken

### ISSUE THREAD

**Issue by jhardenberg** [DestinE-Climate-DT/Climate-DT-catalog#74]
The file [main.yaml](https://github.com/DestinE-Climate-DT/Climate-DT-catalog/blob/main/catalogs/lumi-phase1/catalog/IFS-NEMO/main.yaml) of the lumi-phase1/IFS-NEMO catalogue is broken, as it contains the following lines:

```
  a1al:
    description: FDB IFS-NEMO tco399-eORCA025 SSP3-7.0 run
    driver: yaml_file_cat
    args:
```
and is missing `args`!
